### root api
GET http://localhost:8000/

### GET 
GET http://localhost:8000/api/v1/task

### Task post 
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task" : " tv",
    "hr":860
    }


### Delete method
DELETE  http://localhost:8000/api/v1/task/625df2f170b6c3b3f5acbe4f


### new api

### create user
GET http://localhost:8000/api/v1/user

### get a user by id
GET http://localhost:8000/api/v1/user/625e2924b02548548f863b61

### update user
POST  http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "UserName": "nishap",
    "Email":"nshs@gmail.com",
    "Password":"123456"
}

### DELETE user
DELETE  http://localhost:8000/api/v1/user/625e2924b02548548f863b61

### PATCH
PATCH http://localhost:8000/api/v1/user
